### ISSUE TITLE
auth

### ISSUE THREAD

**Issue by p07chju57** [borisagbo/Plannings#1]
#1 Bon explique moi ce que tu veux faire avec l'authentification
#2  Pour la base de données les mots de passe doivent etres crypté 
#1  Pour les droits des admins c'est mieux de le faire avec un champ de types entiers

**Comment by borisagbo** [comment]
> #1 Bon explique moi ce que tu veux faire avec l'authentification
> #2 Pour la base de données les mots de passe doivent etres crypté
> #1 Pour les droits des admins c'est mieux de le faire avec un champ de types entiers

Bien reçu du auras la réponse à ta question le dimanche 14h30

**Comment by borisagbo** [comment]
- j'ai pas bien compris la question #1
-Pour les mots de passe j'aimerai passer l'étape de l'authentification avant de le crypter
-j' pas bien saisi la proposition , je veux plus de détail merci

**Comment by p07chju57** [comment]
les mots de passes doivent etre d'abord crypter avant de faire l'insertion dans la base de donnée

**Comment by p07chju57** [comment]
deuxio pour un systeme correct de gestion d'utilisateurs c'est mieux d'avoir une autre table qui a les informations des differents compte

**Comment by p07chju57** [comment]
C'est quoi le m dans le login.php

**Comment by borisagbo** [comment]
> C'est quoi le m dans le login.php

c'est l'identifiant des users par rapport à leurs statu, il est envoyer quand l'utilisateur choisie sont option de connexion à l’accueil

**Comment by p07chju57** [comment]
je vais tester ton code là

**Comment by p07chju57** [comment]
En faite t'a pas vraiment travailler sur le projet quoi ?
ok
