### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by p07chju57** [borisagbo/Plannings#2]
revoie la nomenclature de ta base de données (le nom de certaines tables est en majuscule)
Mauvaise modelisation car t'as oublié de prendre en compte que un plannings concerne une filière et un etudiant aussi appartient à une filiere

**Comment by borisagbo** [comment]
> revoie la nomenclature de ta base de données (le nom de certaines tables est en majuscule)
> Mauvaise modelisation car t'as oublié de prendre en compte que un plannings concerne une filière et un etudiant aussi appartient à une filiere

Reçu 5/5

**Comment by borisagbo** [comment]
#1 les fileries sont intégrer dans les tables étudiant et plannning 
La nomenclature est régularisé tu auras le nouveau commit après la synchronisation des comptes;
merci
